/*        Generated by TAPENADE     (INRIA, Tropics team)
    Tapenade 3.6 (r4343) - 10 Feb 2012 10:52


  Differentiation of pow in forward (tangent) mode:
   variations   of useful results: pow
   with respect to varying inputs: a
*/
// TAPENADE friendly version of pow()
double pow_d(double a, double ad, double b, double *pow) {
    double c;
    double cd;
    double epsilon;
    double result1;
    double arg1;
    double arg1d;
    epsilon = 1.0e-10;
    result1 = fabs(a);
    if (result1 < epsilon && a >= 0.0) {
        arg1d = b*ad/(a+epsilon);
        arg1 = b*log(a+epsilon);
        cd = arg1d*exp(arg1);
        c = exp(arg1);
    } else {
        result1 = fabs(a);
        if (result1 < epsilon && a < 0.0) {
            arg1d = b*ad/(a-epsilon);
            arg1 = b*log(a-epsilon);
            cd = arg1d*exp(arg1);
            c = exp(arg1);
        } else {
            arg1d = b*ad/a;
            arg1 = b*log(a);
            cd = arg1d*exp(arg1);
            c = exp(arg1);
        }
    }
    *pow = c;
    return cd;
}
